name: test-build-wheels-linux

on:
  push:
    branches:
      - wheel
  workflow_dispatch:

env:
  SHERPA_ONNX_IS_IN_GITHUB_ACTIONS: 1

concurrency:
  group: build-wheels-linux-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels_linux:
    name: ${{ matrix.manylinux }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["cp313"]
        manylinux: [manylinux_2_28]

    steps:
      - uses: actions/checkout@v4

      - name: Update version
        shell: bash
        run: |
          ./new-release.sh
          git diff .

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_BUILD: "cp313-manylinux_x86_64"

          CIBW_BEFORE_BUILD: pip install setuptools wheel cmake

          CIBW_BEFORE_ALL: |
            yum install -y pkgconfig alsa-lib-devel
            git clone --depth 1 --branch v1.2.12 github.com
            cd alsa-lib
            ./gitcompile
            make install
            cd ..

          CIBW_ENVIRONMENT: >
            CPLUS_INCLUDE_PATH=/project/alsa-lib/include:$CPLUS_INCLUDE_PATH 
            SHERPA_ONNX_ALSA_LIB_DIR=/project/alsa-lib/src/.libs 
            SHERPA_ONNX_ENABLE_ALSA=1 
            SHERPA_ONNX_MAKE_ARGS="VERBOSE=1"

          CIBW_BUILD_VERBOSITY: 3
          CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/${{ matrix.manylinux }}_x86_64

      - name: Display wheels
        shell: bash
        run: |
          ls -lh ./wheelhouse/

      - name: Install patchelf
        run: |
          sudo apt-get update -q
          sudo apt-get install -q -y patchelf

      - name: Patch wheels
        shell: bash
        run: |
          mkdir -p ./wheels_out
          sudo python3 ./scripts/wheel/patch_wheel.py --in-dir ./wheelhouse --out-dir ./wheels_out
          
          ls -lh ./wheels_out/
          rm -rf ./wheelhouse
          mv ./wheels_out ./wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.python-version }}-${{ matrix.manylinux }}
          path: ./wheelhouse/*.whl
